#!/usr/bin/env python3
"""YouMod の設定画面を日本語化する ja.lproj/Localizable.strings を作る。

en.lproj の全キーを走査し、下の対訳表 JA にあるものは日本語、無いものは
英語の原文をそのまま値に入れる。呼び出し側は「見つからなければ鍵名を返す」
作りなので、キーを欠落させると画面に AUTO_FULLSCREEN のような内部名が出る。

上流が更新されて新しいキーが増えたら、JA に足して再実行すれば当て直せる。

    python tools/youmod-ja.py [--bundle <YouMod.bundle のパス>]
"""
import argparse
import plistlib
import sys
from pathlib import Path

DEFAULT_BUNDLE = Path(
    r"C:\Users\rutoi\AppData\Local\Temp\youmod\var\jb\Library"
    r"\Application Support\YouMod.bundle"
)

# 対訳表。値の \n は原文と同じくリテラルの 2 文字(バックスラッシュ + n)。
# %@ %d などの書式指定子は数と順番を原文から変えないこと。
JA = {
    "ADD_SHORTS_DOWNLOAD": "ショートにダウンロードボタンを追加",
    "ADD_SHORTS_DOWNLOAD_DESC": "ショート動画のプレイヤー上にダウンロードボタンを追加します。",
    "ALREADY_DOWNLOADING": "すでにダウンロード中です",
    "ALWAYS_SHOW_REMAINING": "残り時間を常に表示",
    "ALWAYS_SHOW_REMAINING_DESC": "プレイヤー上に残り時間を常に表示します。",
    "APPEARANCE": "外観",
    "APPLY_DESC": "アプリの再起動が必要です。今すぐ再起動しますか?",
    "ARE_YOU_THERE_DIALOG": "「動画を視聴していますか?」を隠す",
    "ARE_YOU_THERE_DIALOG_DESC": "アプリを長時間操作しないときに出るダイアログを隠します。",
    "AUDIO_SAVED": "音声を保存しました",
    "AUDIO_TRACK": "優先する音声トラック",
    "AUDIO_TRACK_SELECT": "選択中の音声トラック",
    "AUDIO_TRACK_SELECT_DESC": "再生に優先して使う音声トラックの言語を指定します(利用できる場合)。",
    "AUTO_CLEARCACHE": "キャッシュを自動削除",
    "AUTO_CLEARCACHE_DESC": "起動時にアプリのキャッシュを自動で削除します。",
    "AUTO_EXIT_FULLSCREEN": "全画面を自動で解除",
    "AUTO_EXIT_FULLSCREEN_DESC": "動画の再生が終わったら全画面表示を自動で解除します。",
    "AUTO_FEED_MUTE": "フィード動画を自動ミュート",
    "AUTO_FEED_MUTE_DESC": "フィードで再生される動画を自動でミュートします。",
    "AUTO_FULLSCREEN": "自動で全画面",
    "AUTO_FULLSCREEN_DESC": "動画の再生を始めたら自動で全画面表示にします。",
    "AUTO_OPEN_LINK": "クリップボードを自動確認",
    "AUTO_OPEN_LINK_DESC": "アプリを開くたびに、クリップボードにYouTube関連のリンクがないか確認します。\\niOSの設定 → YouTube → ほかのAppからペースト で「許可」を選ぶ必要があります",
    "BACKGROUND_PLAYBACK": "バックグラウンド再生",
    "BACKGROUND_PLAYBACK_DESC": "動画のバックグラウンド再生を有効にします。",
    "BEST": "最高",
    "BLOCK_UPGRADE_DIALOGS": "アップデート案内を遮断",
    "BLOCK_UPGRADE_DIALOGS_DESC": "アプリの更新を促すYouTubeのダイアログを遮断します。",
    "BOTTOM": "下",
    "CACHE": "キャッシュ管理",
    "CANCEL": "キャンセル",
    "CANNOT_SAVE_TO_PHOTOS": "写真に保存できません",
    "CAPTIONS_FAILED": "字幕のダウンロードに失敗しました",
    "CAPTION_BUTTON": "字幕",
    "CAPTION_TRACK": "優先する字幕",
    "CAPTION_TRACK_SELECT": "選択中の字幕",
    "CAPTION_TRACK_SELECT_DESC": "表示に優先して使う字幕の言語を指定します(利用できる場合)。",
    "CHOOSE_DOWNLOAD_SERVER": "ダウンロードサーバーを選択",
    "CLEARCACHE": "キャッシュを削除",
    "CONNECTING_TO_SERVER": "サーバーに接続中...",
    "CONTROL_CENTER": "コントロールセンター",
    "CONVERTING": "変換中:",
    "COPIED_AUTHOR": "投稿者をコピーしました",
    "COPIED_DESCRIPTION": "概要欄をコピーしました",
    "COPIED_TITLE": "タイトルをコピーしました",
    "COPIED_TO_CLIPBOARD": "クリップボードにコピーしました",
    "COPIED_VID_INFO": "動画情報をすべてコピーしました",
    "COPY": "コピー",
    "COPY_ALL_VID_INFO": "すべてコピー",
    "COPY_AUTHOR": "投稿者をコピー",
    "COPY_COMMENT_IMAGE": "コメントを画像でコピー",
    "COPY_COMMENT_TEXT": "コメントの本文をコピー",
    "COPY_CURRENT_IMAGE": "表示中の画像をコピー",
    "COPY_DESCRIPTION": "概要欄をコピー",
    "COPY_POST_IMAGE": "投稿を画像でコピー",
    "COPY_POST_TEXT": "投稿の本文をコピー",
    "COPY_THUMBNAIL": "サムネイルをコピー",
    "COPY_TIMESTAMP_ON_PAUSE": "時間指定リンクをコピー",
    "COPY_TIMESTAMP_ON_PAUSE_DESC": "一時停止ボタンを押すと、再生位置つきのリンクをクリップボードにコピーできます。",
    "COPY_TITLE": "タイトルをコピー",
    "COPY_URL": "動画リンクをコピー",
    "COPY_URL_TIMESTAMP": "時間指定つきで動画リンクをコピー",
    "COPY_VID_INFO": "動画情報をコピー",
    "COURSE_TAB": "コース",
    "CREATE_TAB": "作成",
    "DEFAULT": "デフォルト",
    "DEFAULT_SPEED": "既定の再生速度",
    "DEFAULT_SPEED_DESC": "既定の再生速度を上書きします。",
    "DEFAULT_TAB": "起動時のタブ",
    "DEVICE_UI": "画面スタイル",
    "DISABLED": "無効",
    "DISABLES_CAPTION_TRACK": "字幕を自動でオフ",
    "DISABLES_CAPTION_TRACK_DESC": "優先する言語が自動生成、または見つからない場合に字幕を自動でオフにします。",
    "DISABLES_DOUBLE_TAP": "ダブルタップを無効化",
    "DISABLES_DOUBLE_TAP_DESC": "プレイヤー上でのダブルタップによるシークを無効にします。",
    "DISABLES_ENGAGE_PANEL": "全画面での情報パネルを無効化",
    "DISABLES_ENGAGE_PANEL_DESC": "全画面表示中に情報パネルが出ないようにします。",
    "DISABLES_LONG_HOLD": "長押しを無効化",
    "DISABLES_LONG_HOLD_DESC": "プレイヤー上での長押しによる倍速再生を無効にします。",
    "DISABLES_NEW_MINIPLAYER": "新しいミニプレーヤーを無効化",
    "DISABLES_NEW_MINIPLAYER_DESC": "新しいミニプレーヤーの代わりに旧式のものを使います。古いバージョンのYouTubeでのみ動作します。",
    "DISABLES_RTL": "RTL表示を無効化",
    "DISABLES_RTL_DESC": "本来は右から左(RTL)に表示される言語を、強制的に左から右(LTR)で表示します。",
    "DISABLES_SHORTS_PIP": "ショートのPiPを無効化",
    "DISABLES_SHORTS_PIP_DESC": "ショートのPiPを無効にしようとします。完全に無効化できない場合があります。",
    "DISABLES_SHOW_REMAINING": "残り時間の表示を無効化",
    "DISABLES_SHOW_REMAINING_DESC": "再生時間をタップしたときに残り時間を表示する機能を無効にします。",
    "DISABLES_SNACK_BAR": "スナックバーを無効化",
    "DISABLES_SNACK_BAR_DESC": "ボタンを押したときなどに画面下部へ出る通知バーを無効にします。",
    "DISABLES_SNAP_TO_CHAPTER": "チャプターへの吸着を無効化",
    "DISABLES_SNAP_TO_CHAPTER_DESC": "シークバーがチャプターの区切りに吸い付かないようにします。",
    "DISABLES_ZOOM": "自由ズーム操作を無効化",
    "DISABLES_ZOOM_DESC": "新しい自由ズームの操作を無効にします。",
    "DISABLE_HINTS": "ヒントを無効化",
    "DISABLE_HINTS_DESC": "チュートリアルのヒントや操作を促すポップアップを無効にします。",
    "DONE": "完了",
    "DOWNLOADING": "ダウンロード中",
    "DOWNLOADING_AUDIO": "音声をダウンロード中...",
    "DOWNLOADING_CAPTIONS": "字幕をダウンロード中...",
    "DOWNLOADING_THUMBNAIL": "サムネイルをダウンロード中...",
    "DOWNLOADING_TO_SERVER": "サーバーにダウンロード中...",
    "DOWNLOADING_VIDEO": "動画をダウンロード中...",
    "DOWNLOAD_AUDIO": "音声をダウンロード",
    "DOWNLOAD_BUTTON": "ダウンロード",
    "DOWNLOAD_CANCELLED": "ダウンロードを中止しました",
    "DOWNLOAD_CAPTIONS": "字幕をダウンロード",
    "DOWNLOAD_COMMENT": "コメント情報を保存",
    "DOWNLOAD_COMMENT_DESC": "三点ボタンを長押しして、コメントの本文をコピーしたり画像として保存できるようにします。",
    "DOWNLOAD_COMPLETED": "ダウンロードが完了しました",
    "DOWNLOAD_FAILED": "ダウンロードに失敗しました",
    "DOWNLOAD_MANAGER": "ダウンロードマネージャー",
    "DOWNLOAD_MANAGER_DESC": "YouTube標準のダウンロード機能をYouModのものに置き換えます。動画・音声・字幕・サムネイルをダウンロードできます。",
    "DOWNLOAD_METHOD": "ダウンロード方式",
    "DOWNLOAD_METHOD_DESC": "動画をどうやって取得するかを選びます。端末内は最新版のYouTubeで動作します。",
    "DOWNLOAD_POST": "投稿情報を保存",
    "DOWNLOAD_POST_DESC": "長押しして、投稿の本文をコピーしたり画像として保存できるようにします。",
    "DOWNLOAD_SERVER": "ダウンロードサーバー",
    "DOWNLOAD_SHORTS": "ショートをダウンロード",
    "DOWNLOAD_VIDEO": "動画をダウンロード",
    "DRC_AUDIO_OPTIONS": "音量の安定化を自動設定",
    "DRC_AUDIO_OPTIONS_DESC": "音量の安定化を有効にするかどうかを自動で選びます。",
    "ENABLED": "有効",
    "ENABLES_SHORTS_QUALITY": "ショートの画質選択を有効化",
    "ENABLES_SHORTS_QUALITY_DESC": "ショートで画質の選択メニューを強制的に使えるようにします。",
    "ENGLISH": "英語",
    "ERROR": "エラー",
    "ERROR_ADS": "広告の再生中は動画リンクをコピーできません",
    "ERROR_INVALID_FILE": "無効なファイルです",
    "ERROR_NO_KEYS_EXPORT": "書き出せる設定がありません",
    "ERROR_NO_KEYS_IMPORT": "読み込める設定がありません",
    "ERROR_VIDEOID": "動画IDを取得できません",
    "EXPORT": "設定を書き出す",
    "EXPORT_DESC": "設定を .plist ファイルに書き出します。",
    "EXTRA": "追加機能",
    "EXTRALARGE": "特大 (+2)",
    "EXTRA_SPEED": "再生速度の選択肢を追加",
    "EXTRA_SPEED_DESC": "再生速度の選択肢を最大10倍まで追加します。",
    "FASHION_TAB": "ファッションと美容",
    "FEED": "フィード",
    "FINA_VIDEO": "動画を仕上げ中...",
    "FIXES_SLOW_MINIPLAYER": "ミニプレーヤーの遅さを改善",
    "FIXES_SLOW_MINIPLAYER_DESC": "ミニプレーヤーから動画を広げるときの遅さを改善します。古いバージョンのYouTubeでのみ動作します。",
    "FIX_PLAYBACK_ISSUES": "再生の不具合を修正(暫定)",
    "FIX_PLAYBACK_ISSUES_DESC": "一部の環境で起きる再生の不具合の修正を試みます。有効にすると、エラーや再生失敗のたびにプレイヤーが自動で再読み込みされます。",
    "FLOATING_KEYBOARD": "フローティングキーボード",
    "FLOATING_KEYBOARD_DESC": "フローティングキーボードを強制的に有効にします。iPad風の表示にしているiPhoneで便利です。\\n注意: iPadスタイルを選んでいるときのみ動作します。",
    "FLYOUT_MENU": "三点メニュー",
    "FORCE_MINIPLAYER": "ミニプレーヤーを強制",
    "FORCE_MINIPLAYER_DESC": "子ども向けの動画を含むすべての動画を、プレイヤーを閉じたときにミニプレーヤーで再生できるようにします。",
    "FORCE_SEEKBAR": "シークバーを常に表示",
    "FORCE_SEEKBAR_DESC": "全画面表示中、シークバーが常に表示されたままになります。",
    "FORSTED_TAB_BAR": "タブバーを半透明にする",
    "FORWARD_SECONDS": "早送りの秒数",
    "GAMING_TAB": "ゲーム",
    "GESTURES": "ジェスチャー操作を有効化",
    "GESTURES_DESC": "動画画面の左右の端を上下にスワイプして、明るさ・音量・再生速度を調整します。",
    "GESTURE_AREA": "ジェスチャーの反応領域",
    "GESTURE_AREA_DESC": "画面の端でジェスチャーが効く範囲を調整します。(50%にすると画面が左右半分に分かれ、中央の無反応な領域がなくなります。)",
    "GESTURE_BRIGHTNESS": "明るさ",
    "GESTURE_HEADER": "ジェスチャー",
    "GESTURE_HUD": "ジェスチャーHUDを表示",
    "GESTURE_HUD_DESC": "明るさ・音量・再生速度を調整するときに、現在の割合(%)を画面に表示します。",
    "GESTURE_HUD_POSITION": "ジェスチャーHUDの位置",
    "GESTURE_HUD_POSITION_DESC": "ジェスチャーHUDの上下の位置を設定します(上・中央・下)。",
    "GESTURE_HUD_SIZE": "ジェスチャーHUDの大きさ",
    "GESTURE_HUD_SIZE_DESC": "ジェスチャーHUDの文字とアイコンの大きさを調整します。",
    "GESTURE_NONE": "なし",
    "GESTURE_SPEED": "再生速度",
    "GESTURE_VOLUME": "音量",
    "HIDE_AUTOPLAY": "自動再生スイッチを隠す",
    "HIDE_AUTOPLAY_DESC": "プレイヤー上の自動再生スイッチを隠します。",
    "HIDE_CAPTIONS_BUTTON": "字幕ボタンを隠す",
    "HIDE_CAPTIONS_BUTTON_DESC": "プレイヤー上の字幕ボタンを隠します。",
    "HIDE_CAST_BUTTON_NAVBAR": "キャストボタンを隠す",
    "HIDE_CAST_BUTTON_NAVBAR_DESC": "ナビゲーションバーのキャストボタンを隠します。",
    "HIDE_CAST_BUTTON_PLAYER": "キャストボタンを隠す",
    "HIDE_CAST_BUTTON_PLAYER_DESC": "プレイヤー上のキャストボタンを隠します。",
    "HIDE_COMMENTS_PREVIEW": "コメントのプレビューを隠す",
    "HIDE_COMMENTS_PREVIEW_DESC": "上位コメントのプレビュー欄を消します。コメント欄そのものは開けます。",
    "HIDE_COMMENTS_SECTION": "コメント欄を隠す",
    "HIDE_COMMENTS_SECTION_DESC": "コメント欄をまるごと消します。",
    "HIDE_COMMU_GUIDE": "コミュニティガイドラインを隠す",
    "HIDE_COMMU_GUIDE_DESC": "コミュニティガイドラインの見出しを隠します。",
    "HIDE_CONTENT_WARNING": "コンテンツの警告をスキップ",
    "HIDE_CONTENT_WARNING_DESC": "一部の動画で出る、センシティブなコンテンツの警告を自動でスキップします。",
    "HIDE_END_SCREEN": "終了画面のカードを隠す",
    "HIDE_END_SCREEN_DESC": "動画が終わる直前に出る終了画面のカードを隠します。",
    "HIDE_ENGAGEMENT_SUBBAR": "コメントの並べ替えを隠す",
    "HIDE_ENGAGEMENT_SUBBAR_DESC": "コメントの並べ替え見出し(人気順・新しい順)を常に表示しないようにします。",
    "HIDE_FEED_POST": "投稿を隠す",
    "HIDE_FEED_POST_DESC": "フィードの投稿を隠します。",
    "HIDE_FULLSCREEN_ACTIONS": "全画面のアクションを隠す",
    "HIDE_FULLSCREEN_ACTIONS_DESC": "全画面表示中のクイックアクションボタン(高評価・低評価・他の動画など)を隠します。",
    "HIDE_FULL_VID_TITLE": "全画面の動画タイトルを隠す",
    "HIDE_FULL_VID_TITLE_DESC": "全画面表示中に左上に出る動画タイトルを隠します。",
    "HIDE_HORI_SHELF": "横スクロールの棚を消す",
    "HIDE_HORI_SHELF_DESC": "フィードの横スクロール表示(ニュース、続きを視聴、投稿のまとめなど)をすべて消します。ただしPlayablesは除きます。",
    "HIDE_LIKE_DISLIKE_VOTES": "高評価/低評価の通知を隠す",
    "HIDE_LIKE_DISLIKE_VOTES_DESC": "動画を高評価/低評価したときに出るメッセージを隠します。",
    "HIDE_MUSIC_PLAYLISTS": "音楽プレイリスト作成を隠す",
    "HIDE_MUSIC_PLAYLISTS_DESC": "フィードの音楽プレイリスト作成(曲調を3つ選ぶもの)を隠します。",
    "HIDE_NEXT_AND_PREV_BUTTON": "前へ/次へボタンを隠す",
    "HIDE_NEXT_AND_PREV_BUTTON_DESC": "プレイヤー上の前へ/次へボタンを隠します。",
    "HIDE_NOTIFICATION_BUTTON": "通知ボタンを隠す",
    "HIDE_NOTIFICATION_BUTTON_DESC": "ナビゲーションバーの通知ボタンを隠します。",
    "HIDE_PAID_OVERLAY": "「プロモーションを含みます」を隠す",
    "HIDE_PAID_OVERLAY_DESC": "プレイヤー上の「プロモーションを含みます」の表示を隠します。",
    "HIDE_PLAYABLES": "Playablesを消す",
    "HIDE_PLAYABLES_DESC": "フィードからPlayables(ミニゲーム)を消します。",
    "HIDE_RELATED_VIDEOS": "関連動画を隠す",
    "HIDE_RELATED_VIDEOS_DESC": "プレイヤーの下に出る関連動画を隠します。(プレイヤー上のものは対象外)",
    "HIDE_SEARCH_BUTTON": "検索ボタンを隠す",
    "HIDE_SEARCH_BUTTON_DESC": "ナビゲーションバーの検索ボタンを隠します。",
    "HIDE_SEARCH_HISTORY": "検索履歴を隠す",
    "HIDE_SEARCH_HISTORY_DESC": "検索バーを使うときに、過去の検索履歴と候補を表示しないようにします。\\n注意: 検索履歴は他のYouTubeアプリからは引き続き見られます。",
    "HIDE_SHORTS_DISCLOSURE": "「報酬を得ています」を隠す",
    "HIDE_SHORTS_DISCLOSURE_DESC": "ショートの「報酬を得ています」という表示を隠します。",
    "HIDE_SHORTS_PRODUCT": "商品を隠す",
    "HIDE_SHORTS_PRODUCT_DESC": "ショート上のタグ付き商品とショッピングリンクを隠します。",
    "HIDE_SHORTS_RECBAR": "おすすめバーを隠す",
    "HIDE_SHORTS_RECBAR_DESC": "ショートのプレイヤーに出るおすすめの操作バー(この音源を使う、ショッピング、コメントのプレビューなど)を隠します。",
    "HIDE_SHORTS_SHELF": "ショートの棚を隠す",
    "HIDE_SHORTS_SHELF_DESC": "フィードのショートの棚を隠します。登録チャンネルタブも含みます。",
    "HIDE_SHORTS_SUBBAR": "サブバーを隠す",
    "HIDE_SHORTS_SUBBAR_DESC": "ショートのプレイヤー上部にある種類バーを隠します。",
    "HIDE_SHORTS_TOPBAR": "トップバーを隠す",
    "HIDE_SHORTS_TOPBAR_DESC": "プレイヤー上部のバーをすべて隠します。",
    "HIDE_STARTUP_ANIMATIONS": "YouTubeの起動アニメーションを隠す",
    "HIDE_STARTUP_ANIMATIONS_DESC": "アプリを開いたときのYouTubeの起動アニメーションを隠します。",
    "HIDE_SUBBAR": "サブバーを隠す",
    "HIDE_SUBBAR_DESC": "フィード上部のサブバーを隠します。",
    "HIDE_SUGGESTED_VIDEO": "おすすめ動画を隠す",
    "HIDE_SUGGESTED_VIDEO_DESC": "動画の再生が終わったときに出る、おすすめ動画の一覧を隠します。",
    "HIDE_SURVEYS": "アンケートを隠す",
    "HIDE_SURVEYS_DESC": "YouTubeが時々表示する動画アンケートを隠します。",
    "HIDE_TAB_INDI": "タブの印を隠す",
    "HIDE_TAB_INDI_DESC": "タブバーのタブの印をすべて隠します。",
    "HIDE_TAB_LABELS": "タブの文字を隠す",
    "HIDE_TAB_LABELS_DESC": "タブバーのタブ名をすべて隠します。",
    "HIDE_VOICE_SEARCH_BUTTON": "音声検索ボタンを隠す",
    "HIDE_VOICE_SEARCH_BUTTON_DESC": "ナビゲーションバーの音声検索ボタンを隠します。",
    "HIDE_WATERMARK": "透かしを隠す",
    "HIDE_WATERMARK_DESC": "プレイヤー下部に出るチャンネルの透かしを隠します。",
    "HISTORY_TAB": "履歴",
    "HOLD_TO_SPEED": "長押しで倍速",
    "HOLD_TO_SPEED_DESC": "長押ししたときの再生速度を自分で設定します。",
    "HOME_TAB": "ホーム",
    "IMPORT": "設定を読み込む",
    "IMPORT_DESC": "設定を .plist ファイルから読み込みます。",
    "IMPORT_DONE": "完了しました",
    "INTERFACE": "インターフェース",
    "KEEP_SHORTS_SUBSCRIPT": "登録チャンネルのショートを残す",
    "KEEP_SHORTS_SUBSCRIPT_DESC": "登録チャンネルタブからショートが消されないようにします。",
    "LANGUAGE": "言語",
    "LARGE": "大 (+1)",
    "LEARNING_TAB": "学習",
    "LEFT_SIDE_GESTURE": "左端のスワイプ操作",
    "LIBRARY_TAB": "ライブラリ (マイページ)",
    "LIKE_TAB": "高く評価した動画",
    "LIVE_TAB": "ライブ",
    "LOCK_SPEED": "速度を固定",
    "LOCK_SPEED_DESC": "下にスワイプして、調整した速度を固定します。",
    "LOOP": "ループ",
    "LOOP_BUTTON": "ループ",
    "LOOP_DISABLED": "ループをオフにしました",
    "LOOP_ENABLED": "ループをオンにしました",
    "MANAGE_OVERLAY_BUTTONS": "プレイヤー上のボタンを管理",
    "MANAGE_OVERLAY_BUTTONS_DESC": "プレイヤー上のボタンの並べ替えと表示切り替え",
    "MANAGE_TABS": "タブを管理",
    "MANAGE_TABS_DESC": "タブの並べ替えと表示切り替え",
    "MAX": "最大 (+3)",
    "MERGING_VID": "動画を結合中...",
    "MERGING_VID_FALLBACK": "代替の方式で動画を結合中...",
    "METHOD_DIRECT": "直接",
    "METHOD_ONDEVICE": "端末内 (SABR)",
    "METHOD_SERVER": "サーバー",
    "MIDDLE": "中央",
    "MINIGAME_TAB": "Playables",
    "MISCELLANEOUS": "その他",
    "MOVIE_TAB": "映画",
    "MUSIC_TAB": "音楽",
    "MUTE_BUTTON": "ミュート",
    "NAVBAR": "ナビゲーションバー",
    "NAVIGATION_ICON": "ナビゲーションのアイコン",
    "NAVIGATION_ICON_DESC": "ナビゲーションバーのYouTubeロゴを変更します。",
    "NEWS_TAB": "ニュース",
    "NEW_ISSUES": "不具合の報告・機能の要望",
    "NEW_ISSUES_DESC": "不具合を見つけた、または新機能の要望があるときはこちらをタップ。",
    "NORMAL": "標準 (デフォルト)",
    "NOTI_TAB": "通知",
    "NO_AUDIO_STREAM_FOUND": "音声ストリームが見つかりません",
    "NO_AUDIO_URL": "音声のURLが見つかりません",
    "NO_AUTO_DUBBED": "元の音声トラックを使う",
    "NO_AUTO_DUBBED_DESC": "優先する言語のトラックが自動吹き替え、または見つからない場合は、元の音声トラックを使います。",
    "NO_CAPTIONS": "この動画に利用できる字幕はありません",
    "NO_CAPTIONS_URL": "有効な字幕のURLが見つかりません",
    "NO_STREAM_URL": "ストリームのURLが見つかりません",
    "NO_THUMBNAIL_FOUND": "サムネイルが見つかりません",
    "NO_VID_AUDIO_STREAM_FOUND": "映像/音声のストリームが見つかりません",
    "OLD_QUALITY_PICKER": "旧式の画質選択を使う",
    "OLD_QUALITY_PICKER_DESC": "画質の選択メニューを従来の形式に戻します(すべての解像度をすぐに一覧表示)。",
    "OLED_KEYBOARD": "OLEDキーボード",
    "OLED_KEYBOARD_DESC": "ダークテーマのとき、キーボードを純粋な黒(OLED)にします。",
    "OLED_THEME": "OLEDダークモード",
    "OLED_THEME_DESC": "アプリのダークテーマに純粋な黒(OLED)を使います。",
    "OPEN_LINK": "リンクを開く",
    "OPEN_VID_BEFORE": "ダウンロードマネージャーを使う前に動画を開いてください",
    "ORIGINAL": "オリジナル",
    "OVERLAY_BUTTON_REORDER_HINT": "ドラッグで並べ替え。スイッチで表示/非表示を切り替えます。",
    "OVERRIDE": "現在の設定を上書きします。続けますか?",
    "PAUSE_ON_OVERLAY": "操作画面で一時停止",
    "PAUSE_ON_OVERLAY_DESC": "プレイヤーの操作画面が出たら再生を一時停止します。",
    "PAUSE_SHORTS": "停止",
    "PAUSE_TWO_FINGERS": "2本指で一時停止",
    "PAUSE_TWO_FINGERS_DESC": "画面を2本指でタップして再生/一時停止を切り替えます。",
    "PERFER": "設定",
    "PERFER_HEADER": "YouModの設定",
    "PHOTO_ACCESS_DENINED": "写真へのアクセスが拒否されました",
    "PLAYBACK_SPEED": "再生速度",
    "PLAYER": "プレイヤー",
    "PLAYER_ACTIONS": "プレイヤーの操作",
    "PLAYLIST_TAB": "再生リスト",
    "PORTRAIT_FULLSCREEN": "縦向きの全画面表示",
    "PORTRAIT_FULLSCREEN_DESC": "縦向きでの全画面表示に対応させます。",
    "POST_ACTION_ASK": "毎回確認",
    "POST_ACTION_SAVE_PHOTOS": "写真に保存",
    "POST_ACTION_SHARE": "共有",
    "POST_DOWNLOAD_ACTION": "ダウンロード後の動作",
    "POST_TAB": "投稿",
    "PREMIUM": "Premium",
    "QUALITY_BUTTON": "画質の操作",
    "QUALITY_CELLULAR": "モバイル通信時の画質",
    "QUALITY_CELLULAR_DESC": "モバイルデータ通信で再生するとき、選んだ画質を自動で適用します。",
    "QUALITY_LOW_POWER": "低電力モード時の画質",
    "QUALITY_LOW_POWER_DESC": "端末が低電力モードのとき、選んだ画質を自動で適用します。",
    "QUALITY_WIFI": "Wi-Fi接続時の画質",
    "QUALITY_WIFI_DESC": "Wi-Fiで再生するとき、選んだ画質を自動で適用します。",
    "REMOVE_AMBIANT": "シネマティックライティングを消す",
    "REMOVE_AMBIANT_DESC": "プレイヤーの背後で光る周囲の光の効果を消します。",
    "REMOVE_CAST_OPTION": "「テレビで見る」を消す",
    "REMOVE_CAST_OPTION_DESC": "三点メニューから「テレビで見る」を消します。",
    "REMOVE_CHANNEL_COMMUNITY_BUTTON": "コミュニティボタンを消す",
    "REMOVE_CHANNEL_COMMUNITY_BUTTON_DESC": "チャンネルのヘッダーにあるコミュニティボタンを消します。",
    "REMOVE_CHANNEL_SPONSOR_BUTTON": "メンバーシップボタンを消す",
    "REMOVE_CHANNEL_SPONSOR_BUTTON_DESC": "フィード・チャンネルのヘッダー・ショートにあるメンバーシップ(参加)ボタンを消します。",
    "REMOVE_CLEARSCREEN_OPTION": "「画面をクリア」を消す",
    "REMOVE_CLEARSCREEN_OPTION_DESC": "三点メニューから「画面をクリア」を消します。",
    "REMOVE_DARK_OVERLAY": "暗くなる効果を消す",
    "REMOVE_DARK_OVERLAY_DESC": "プレイヤーの操作画面が出たときに画面が暗くなる効果を消します。",
    "REMOVE_DONT_RECOMMEND_OPTION": "「チャンネルをおすすめに表示しない」を消す",
    "REMOVE_DONT_RECOMMEND_OPTION_DESC": "三点メニューから「チャンネルをおすすめに表示しない」を消します。",
    "REMOVE_DOWNLOAD_OPTION": "「動画をダウンロード」を消す",
    "REMOVE_DOWNLOAD_OPTION_DESC": "三点メニューから「動画をダウンロード」を消します。",
    "REMOVE_FEED_BACK_OPTION": "「フィードバックを送信」を消す",
    "REMOVE_FEED_BACK_OPTION_DESC": "三点メニューから「フィードバックを送信」を消します。",
    "REMOVE_FILTER_OPTION": "「検索フィルタ」を消す",
    "REMOVE_FILTER_OPTION_DESC": "三点メニューから「検索フィルタ」を消します。",
    "REMOVE_HELP_OPTION": "「ヘルプとフィードバック」を消す",
    "REMOVE_HELP_OPTION_DESC": "三点メニューから「ヘルプとフィードバック」を消します。",
    "REMOVE_HIDE_FROM_PLAYLIST_OPTION": "「再生リストから動画を非表示」を消す",
    "REMOVE_HIDE_FROM_PLAYLIST_OPTION_DESC": "三点メニューから「再生リストから動画を非表示」を消します。",
    "REMOVE_INFO_OPTION": "「この動画が表示される理由」を消す",
    "REMOVE_INFO_OPTION_DESC": "三点メニューから「この動画が表示される理由」を消します。",
    "REMOVE_LIVE_SHORTS": "ライブ動画を消す",
    "REMOVE_LIVE_SHORTS_DESC": "フィードからライブ動画を消します。",
    "REMOVE_NOTIFY_OPTION": "「通知を受け取る」を消す",
    "REMOVE_NOTIFY_OPTION_DESC": "三点メニューから「通知を受け取る」を消します。",
    "REMOVE_NOT_INTERESTED_OPTION": "「興味なし」を消す",
    "REMOVE_NOT_INTERESTED_OPTION_DESC": "三点メニューから「興味なし」を消します。",
    "REMOVE_PLAY_IN_LAST_QUEUE_OPTION": "「最後に再生」を消す",
    "REMOVE_PLAY_IN_LAST_QUEUE_OPTION_DESC": "三点メニューから「最後に再生」を消します。",
    "REMOVE_PLAY_IN_NEXT_QUEUE_OPTION": "「次に再生」を消す",
    "REMOVE_PLAY_IN_NEXT_QUEUE_OPTION_DESC": "三点メニューから「次に再生」を消します。",
    "REMOVE_POSTS_SHORTS": "投稿を消す",
    "REMOVE_POSTS_SHORTS_DESC": "フィードから投稿を消します。",
    "REMOVE_REMOVE_FROM_PLAYLIST_OPTION": "「再生リストから削除」を消す",
    "REMOVE_REMOVE_FROM_PLAYLIST_OPTION_DESC": "三点メニューから「再生リストから削除」を消します。",
    "REMOVE_REPORT_OPTION": "「報告」を消す",
    "REMOVE_REPORT_OPTION_DESC": "三点メニューから「報告」を消します。",
    "REMOVE_SAVE_OPTION": "「再生リストに保存」を消す",
    "REMOVE_SAVE_OPTION_DESC": "三点メニューから「再生リストに保存」を消します。",
    "REMOVE_SHARE_OPTION": "「共有」を消す",
    "REMOVE_SHARE_OPTION_DESC": "三点メニューから「共有」を消します。",
    "REMOVE_SHORTS_COMMENT_BUTTON": "コメントボタンを消す",
    "REMOVE_SHORTS_COMMENT_BUTTON_DESC": "ショートのプレイヤー上からコメントボタンを消します。",
    "REMOVE_SHORTS_LIKE_BUTTON": "高評価ボタンを消す",
    "REMOVE_SHORTS_LIKE_BUTTON_DESC": "ショートのプレイヤー上から高評価ボタンを消します。",
    "REMOVE_SHORTS_PAUSED_LENS_BUTTON": "レンズボタンを消す",
    "REMOVE_SHORTS_PAUSED_LENS_BUTTON_DESC": "ショートの一時停止中のヘッダーからレンズボタンを消します。",
    "REMOVE_SHORTS_PAUSED_LIVE_BUTTON": "ライブボタンを消す",
    "REMOVE_SHORTS_PAUSED_LIVE_BUTTON_DESC": "ショートの一時停止中のヘッダーからライブボタンを消します。",
    "REMOVE_SHORTS_PAUSED_SUB_BUTTON": "登録チャンネルボタンを消す",
    "REMOVE_SHORTS_PAUSED_SUB_BUTTON_DESC": "ショートの一時停止中のヘッダーから登録チャンネルボタンを消します。",
    "REMOVE_SHORTS_PAUSED_TRENDS_BUTTON": "トレンドボタンを消す",
    "REMOVE_SHORTS_PAUSED_TRENDS_BUTTON_DESC": "ショートの一時停止中のヘッダーからトレンドボタンを消します。",
    "REMOVE_SHORTS_REMIX_BUTTON": "リミックスボタンを消す",
    "REMOVE_SHORTS_REMIX_BUTTON_DESC": "ショートのプレイヤー上からリミックスボタンを消します。",
    "REMOVE_SHORTS_SHARE_BUTTON": "共有ボタンを消す",
    "REMOVE_SHORTS_SHARE_BUTTON_DESC": "ショートのプレイヤー上から共有ボタンを消します。",
    "REMOVE_SHORTS_SOUNDMETADATA_BUTTON": "音源情報ボタンを消す",
    "REMOVE_SHORTS_SOUNDMETADATA_BUTTON_DESC": "ショートのプレイヤー上から音源情報ボタンを消します。",
    "REMOVE_SHUFFLE_OPTION": "「シャッフル」を消す",
    "REMOVE_SHUFFLE_OPTION_DESC": "三点メニューから「シャッフル」を消します。",
    "REMOVE_UN_SUB_OPTION": "「登録解除」を消す",
    "REMOVE_UN_SUB_OPTION_DESC": "三点メニューから「登録解除」を消します。",
    "REMOVE_VIDEO_CLIP_BUTTON": "クリップボタンを消す",
    "REMOVE_VIDEO_CLIP_BUTTON_DESC": "プレイヤーの下と全画面の操作画面からクリップボタンを消します。",
    "REMOVE_VIDEO_DISLIKE_BUTTON": "低評価ボタンを消す",
    "REMOVE_VIDEO_DISLIKE_BUTTON_DESC": "プレイヤーの下と全画面の操作画面から低評価ボタンを消します。",
    "REMOVE_VIDEO_DOWNLOAD_BUTTON": "ダウンロードボタンを消す",
    "REMOVE_VIDEO_DOWNLOAD_BUTTON_DESC": "プレイヤーの下と全画面の操作画面からダウンロードボタンを消します。",
    "REMOVE_VIDEO_LIKE_BUTTON": "高評価ボタンを消す",
    "REMOVE_VIDEO_LIKE_BUTTON_DESC": "プレイヤーの下と全画面の操作画面から高評価ボタンを消します。",
    "REMOVE_VIDEO_LIVE_CHAT_BUTTON": "ライブチャットボタンを消す",
    "REMOVE_VIDEO_LIVE_CHAT_BUTTON_DESC": "プレイヤーの下と全画面の操作画面からライブチャットボタンを消します。",
    "REMOVE_VIDEO_REMIX_BUTTON": "リミックスボタンを消す",
    "REMOVE_VIDEO_REMIX_BUTTON_DESC": "プレイヤーの下と全画面の操作画面からリミックスボタンを消します。",
    "REMOVE_VIDEO_SAVE_BUTTON": "保存ボタンを消す",
    "REMOVE_VIDEO_SAVE_BUTTON_DESC": "プレイヤーの下と全画面の操作画面から、再生リストに保存するボタンを消します。",
    "REMOVE_VIDEO_SHARE_BUTTON": "共有ボタンを消す",
    "REMOVE_VIDEO_SHARE_BUTTON_DESC": "プレイヤーの下と全画面の操作画面から共有ボタンを消します。",
    "REMOVE_WATCH_LATER_OPTION": "「後で見るに保存」を消す",
    "REMOVE_WATCH_LATER_OPTION_DESC": "三点メニューから「後で見るに保存」を消します。",
    "REMOVE_YOUTUBE_MUSIC_OPTION": "「YouTube Musicで聴く」を消す",
    "REMOVE_YOUTUBE_MUSIC_OPTION_DESC": "三点メニューから「YouTube Musicで聴く」を消します。",
    "REMOVE_YTLOGO": "ロゴを消す",
    "REPLACE_PREVNEXT_BUTTONS": "前へ/次へボタンを置き換える",
    "REPLACE_PREVNEXT_BUTTONS_DESC": "プレイヤーの前の動画/次の動画ボタンを、巻き戻し/早送りボタンに置き換えます。",
    "RESETDEFAULT": "すべての設定を初期状態に戻します。続けますか?",
    "RESTORE": "設定を初期化",
    "RESTORE_DESC": "インストール直後と同じ初期設定に戻します。",
    "REWIND_SECONDS": "巻き戻しの秒数",
    "RIGHT_SIDE_GESTURE": "右端のスワイプ操作",
    "SAVED_TO_PHOTOS": "写真に保存しました",
    "SAVE_COMMENT_IMAGE": "コメントを画像で保存",
    "SAVE_CURRENT_IMAGE": "表示中の画像を保存",
    "SAVE_FAILED": "保存に失敗しました",
    "SAVE_POST_IMAGE": "投稿を画像で保存",
    "SAVE_THUMBNAIL": "サムネイルを保存",
    "SB_ACTION_ASK": "スキップ前に確認",
    "SB_ACTION_AUTO_SKIP": "自動でスキップ",
    "SB_ACTION_DISABLE": "無効",
    "SB_ACTION_DISPLAY": "シークバーに表示のみ",
    "SB_ACTION_SKIP_TO": "区間まで移動",
    "SB_CATEGORIES_HEADER": "区間のカテゴリ",
    "SB_CAT_filler": "余談・尺稼ぎ",
    "SB_CAT_filler_DESC": "本題と直接関係のない脱線、冗談、尺稼ぎの部分。",
    "SB_CAT_hook": "導入・あいさつ",
    "SB_CAT_hook_DESC": "これから始まる内容の予告、あいさつや締めの言葉。",
    "SB_CAT_interaction": "視聴者への呼びかけ",
    "SB_CAT_interaction_DESC": "高評価・チャンネル登録・SNSのフォローを促す部分。",
    "SB_CAT_intro": "イントロ",
    "SB_CAT_intro_DESC": "動画の冒頭によくある幕間やオープニングアニメーション。",
    "SB_CAT_music_offtopic": "音楽以外",
    "SB_CAT_music_offtopic_DESC": "音楽動画の中の音楽以外の部分(トーク、前置きなど)。",
    "SB_CAT_outro": "エンドカード",
    "SB_CAT_outro_DESC": "動画の終わりのエンドカード、クレジット、締めの部分。",
    "SB_CAT_poi_highlight": "ハイライト",
    "SB_CAT_poi_highlight_DESC": "動画の要となる場面。「区間まで移動」を選ぶとそこへ直接ジャンプできます。",
    "SB_CAT_preview": "振り返り・予告",
    "SB_CAT_preview_DESC": "別の動画や前回の内容の振り返り、または予告。",
    "SB_CAT_selfpromo": "自己宣伝",
    "SB_CAT_selfpromo_DESC": "投稿者自身の商品・グッズ・他のコンテンツの、報酬を伴わない宣伝。",
    "SB_CAT_sponsor": "スポンサー",
    "SB_CAT_sponsor_DESC": "投稿者と直接関係のない商品やサービスの、報酬を伴う宣伝。",
    "SB_DESCRIPTION": "利用者が投稿したデータを使って、スポンサー区間を自動でスキップします。",
    "SB_DETECTED": "%@ の区間を検出しました。\\nこの区間をスキップしますか?",
    "SB_ENABLE": "SponsorBlockを有効にする",
    "SB_ENABLE_DESC": "SponsorBlock拡張を有効にして、スポンサー区間をスキップします。",
    "SB_HAPTIC_FEEDBACK": "触覚フィードバック",
    "SB_HAPTIC_FEEDBACK_DESC": "区間をスキップしたときに振動で知らせます。",
    "SB_JUMPED_TO_HIGHLIGHT": "ハイライトへ移動しました",
    "SB_JUMP_TO_HIGHLIGHT": "ハイライトがあります。その位置へ移動しますか?",
    "SB_MIN_DURATION_SLIDER": "スキップする区間の最短の長さ",
    "SB_SECTION_MAIN": "基本",
    "SB_SEGMENTS_IN_FEED": "フィードでの区間表示",
    "SB_SEGMENTS_IN_FEED_DESC": "フィードのプレイヤーのシークバーに色つきの区間を表示します。",
    "SB_SEGMENTS_IN_MINIPLAYER": "ミニプレーヤーでの区間表示",
    "SB_SEGMENTS_IN_MINIPLAYER_DESC": "ミニプレーヤーのシークバーに色つきの区間を表示します。",
    "SB_SEGMENTS_IN_PLAYER": "プレイヤーでの区間表示",
    "SB_SEGMENTS_IN_PLAYER_DESC": "通常のプレイヤーのシークバーに色つきの区間を表示します。",
    "SB_SEGMENT_COLOR": "区間の色",
    "SB_SEGMENT_COLOR_SUFFIX": "区間の色",
    "SB_SHOW_BUTTON": "プレイヤー上にボタンを表示",
    "SB_SHOW_BUTTON_DESC": "プレイヤー上にSponsorBlockの切り替えボタンを表示します。",
    "SB_SHOW_DURATION": "区間を除いた再生時間を表示",
    "SB_SHOW_DURATION_DESC": "スキップ対象の区間を除いた動画全体の長さを表示します。",
    "SB_SHOW_NOTIFICATIONS": "通知を表示",
    "SB_SHOW_NOTIFICATIONS_DESC": "区間をスキップしたときに通知を表示します。手動スキップのカテゴリの通知は常に表示されます。",
    "SB_SKIPPED": "%@ の区間をスキップしました",
    "SB_SKIP_ALERT_DURATION": "スキップ通知の表示時間",
    "SB_SKIP_NOW": "スキップ",
    "SB_UNSKIP": "スキップを取り消す",
    "SB_UNSKIP_ALERT_DURATION": "スキップ取り消し通知の表示時間",
    "SEARCH": "検索",
    "SEARCH_DESC": "YouModの設定を検索します。",
    "SEEK_ON_OVERLAY": "操作画面でシーク",
    "SEEK_ON_OVERLAY_DESC": "プレイヤーの操作画面を左右にスワイプして再生位置を動かせるようにします。",
    "SELECT_LANG": "言語を選択",
    "SELECT_MANUALLY": "手動で選択",
    "SERVER_ASIA1": "タイ - アジア",
    "SERVER_EUROPRE1": "ヨーロッパ",
    "SETTINGS": "設定",
    "SHARE_BUTTON": "共有",
    "SHORTS": "ショート",
    "SHORTS_ACTION": "再生が終わったあとの動作",
    "SHORTS_FULLSCREEN": "ピンチで全画面",
    "SHORTS_FULLSCREEN_DESC": "ピンチイン/ピンチアウトで操作画面の表示を切り替え、ショートを全画面で表示します。",
    "SHORTS_ONLY": "ショート専用モード",
    "SHORTS_ONLY_DESC": "YouTubeの機能をショートの視聴だけに制限します。ショートのプレイヤーで2本指で長押しすると解除できます。",
    "SHORTS_ONLY_DISABLED": "ショート専用モードをオフにしました",
    "SHORTS_TAB": "ショート",
    "SHOW_OPTIONS": "選択肢を表示",
    "SHOW_REMAINING_EXTRA": "終了予定時刻も表示",
    "SHOW_REMAINING_EXTRA_DESC": "プレイヤー上の表示に、再生が終わる予定の時刻を追加します。",
    "SHOW_SHORTS_SEEKBAR": "シークバーを常に表示",
    "SHOW_SHORTS_SEEKBAR_DESC": "ショートのプレイヤー下部にシークバーを常に表示します。",
    "SHOW_THUMBNAIL": "サムネイルを表示",
    "SKIP_BACKWARD": "巻き戻し",
    "SKIP_BACKWARD_DESC": "コントロールセンターの前の曲ボタンを、指定した秒数だけ巻き戻すボタンに置き換えます。",
    "SKIP_FORWARD": "早送り",
    "SKIP_FORWARD_DESC": "コントロールセンターの次の曲ボタンを、指定した秒数だけ早送りするボタンに置き換えます。",
    "SKIP_TO_NEXT_SHORTS": "次へ進む",
    "SMALL": "小 (-1)",
    "SOURCE_CODES": "ソースコード",
    "SOURCE_CODES_DESC": "コードを見てみよう!",
    "SPEED_BUTTON": "速度の操作",
    "SPONSORBLOCK_BUTTON": "SponsorBlock",
    "SPORTS_TAB": "スポーツ",
    "STICKY_NAVBAR": "ナビゲーションバーを固定",
    "STICKY_NAVBAR_DESC": "下にスクロールしてもナビゲーションバーが表示されたままになります。",
    "STOP_AUTOPLAY_VIDEO": "自動再生を無効化",
    "STOP_AUTOPLAY_VIDEO_DESC": "動画を開いたときに自動で再生が始まらないようにします。",
    "SUBSCRIPTIONS_TAB": "登録チャンネル",
    "TABBAR": "タブバー",
    "TAB_LIMIT": "タブの上限",
    "TAB_LIMIT_DESC": "タブは6個までです。",
    "TAB_REORDER_HINT": "ドラッグで並べ替え。スイッチで表示/非表示を切り替えます。\\nタブの設定は、タブバーの一番左のタブを長押ししても開けます。",
    "TAP_TO_SEEK": "タップでシーク",
    "TAP_TO_SEEK_DESC": "シークバーをタップして、好きな位置にすぐ移動できます。",
    "THUMBNAIL_FAILED": "サムネイルの取得に失敗しました",
    "THUMBNAIL_OPTIONS": "サムネイルをダウンロード",
    "TOP": "上",
    "TRANSLATE_COMMENT": "コメントを翻訳",
    "TRANSLATE_FAILED": "翻訳に失敗しました。もう一度お試しください。",
    "TRANSLATE_POST": "投稿を翻訳",
    "TRANSLATING": "翻訳中...",
    "TRANSLATION": "翻訳",
    "TRIMMING_AUDIO": "音声を切り出し中...",
    "URL_COPIED": "動画リンクをコピーしました",
    "URL_TIMESTAMP_COPIED": "時間指定つきで動画リンクをコピーしました",
    "USES_24_HOURS_TIME": "24時間表示",
    "USES_24_HOURS_TIME_DESC": "終了予定時刻を24時間表示にします。",
    "VIDEO_TAB": "自分の動画",
    "WARNING": "警告",
    "WATCH_LATER_TAB": "後で見る",
    "YES": "はい",
    "YOUTUBE": "YouTube",
    "ZERO_TAB_DESC": "タブは最低1つ有効にする必要があります。",
}


def build(bundle: Path) -> tuple[int, int, list[str]]:
    """en.lproj を読んで ja.lproj を書き出す。(訳した数, 英語のまま, 未使用の鍵)"""
    src = bundle / "en.lproj" / "Localizable.strings"
    with src.open("rb") as f:
        en = plistlib.load(f)

    ja = {}
    translated = 0
    for key, value in en.items():
        if key in JA:
            ja[key] = JA[key]
            translated += 1
        else:
            ja[key] = value  # 未訳は英語の原文。鍵名を値にすると画面に内部名が出る

    dst_dir = bundle / "ja.lproj"
    dst_dir.mkdir(exist_ok=True)
    with (dst_dir / "Localizable.strings").open("wb") as f:
        plistlib.dump(ja, f, fmt=plistlib.FMT_BINARY)

    stale = sorted(set(JA) - set(en))
    return translated, len(en) - translated, stale


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", type=Path, default=DEFAULT_BUNDLE)
    args = ap.parse_args()

    translated, kept, stale = build(args.bundle)
    print(f"訳した: {translated} 件 / 英語のまま: {kept} 件")
    if stale:
        print(f"en.lproj に無い対訳: {len(stale)} 件 -> {', '.join(stale)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
